# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Script to convert'
        # Default value if no value is explicitly provided
        default: 'hello_world'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: clone repo
      run: git clone https://github.com/DonFlymoor/voxTalkz-Converter/
    - name: Copy audio files to home
      run: |
        mkdir ~/.voxtalkz/
        mkdir ~/.voxtalkz/soundEffects/
        cp voxTalkz-Converter/soundEffect/* ~/.voxtalkz/soundEffects/
    - name: install deps
      run: pip install voxtalkz
    - name: run voxtalkz
      run: python -m voxtalkz scripts/${{ github.event.inputs.name }} ${{ github.event.inputs.name }} --debug --cloud 'AIzaSyBm7NinfOuybtq-WWkcFMoiHHxMz60qxj0'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.1
      with:
        # Artifact name
        name: ${{ github.event.inputs.name }}.mp3 # optional
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{ github.event.inputs.name }}.mp3
